### ISSUE TITLE
screen shot error

### ISSUE THREAD

**Issue by navaneetharaopy** [AndrewFromMelbourne/raspi2png#10]
Board: raspberry pi - 2
OS:  Raspbian wheezy
Setup: Omxplayer with `--win` option running video and browser open at the back.

If i take screenshot  in this setup(mentioned above) i get following error

```
$ ./grabdisplay
tvservice-client: Failed to connect to TV service: -1
./grabdisplay: unable to get display information
```

I have this [link](https://github.com/raspberrypi/firmware/issues/373) which says "gencmd service is limited to 4 concurrent clients". Is there any solution for this?
like checking `bcm_host_init()` before loading

**Comment by AndrewFromMelbourne** [comment]
I will have a look. No promises though.

**Comment by navaneetharaopy** [comment]
Ok, Thanks

**Comment by AndrewFromMelbourne** [comment]
Hi, unfortunately I have run out of ideas. It is the call to bcm_host_init() that fails, but if I don't call it then the call just fails later on. I believe it is a limitation of the DispmanX API.

**Comment by navaneetharaopy** [comment]
Ok

**Comment by navaneetharaopy** [comment]
can we check whether bcm_host_init is already available and  if not initialize by calling `bcm_host_init()`.

Just like header file defination 
`#ifndef SOME_HEADER_FILE_H`
`#define SOME_HEADER_FILE_H`

**Comment by AndrewFromMelbourne** [comment]
Unfortunately no. I actually tried just not calling bcm_host_init(), but as I said above the code just fails later on.
