### ISSUE TITLE
How to isolate a single window using -D (Display)

### ISSUE THREAD

**Issue by dbhower** [AndrewFromMelbourne/raspi2png#11]
Is there a way (using the -D switch) to output a single window vs. the whole screen?

**Comment by AndrewFromMelbourne** [comment]
No, unfortunately not. The snapshot is at a much lower level, where there are no concepts of windows.

**Comment by ewnd9** [comment]
@dbhower you could get coordinates of window via `xwininfo` and then crop fullscreen image

**Comment by dbhower** [comment]
I'm looking for a way to do this automatically.  My code already knows the window name, location, and size.

Thanks
-----ewnd9 <notifications@github.com> wrote: ----- 
To: AndrewFromMelbourne/raspi2png <raspi2png@noreply.github.com>

**Comment by ewnd9** [comment]
If you already knew location and size `imagemagick` will easily do the job by 1 command
