### ISSUE TITLE
Install this?

### ISSUE THREAD

**Issue by Junior1544** [AndrewFromMelbourne/raspi2png#15]
I am brand new to Raspberry Pi and linux all together...

Can i get some better installation instructions? 

You make the assumption that we all know how to clone a git onto the raspberry pi but I am still very much a newbie and can't figure that part out...

Also, for the other tool you say is needed, i tried to apt-get it as you did put, but it tells me that it's already there but needs to be manually installed?  Does this mean that this isn't needed any more, or that different instructions would be needed?

Thank you everyone for any help!
(I think I'll go get a binky, i'm feeling like a baby to this stuff!)

**Comment by Naohiro2g** [comment]
for the reference:

$ sudo apt-get install libpng12-dev
$ wget https://github.com/AndrewFromMelbourne/raspi2png/archive/master.zip
$ unzip master.zip
$ cd raspi2png-master
$ make
$ sudo cp raspi2png /usr/local/bin
