### ISSUE TITLE
raspi2config not saving all the screen in fullhd with RASPBIAN STRETCH

### ISSUE THREAD

**Issue by matteoraggi** [AndrewFromMelbourne/raspi2png#16]
Hi, I am using raspi2config with some RASPBIAN STRETCH WITH DESKTOP Raspberry pi 3 model B and it is all right, it works well, apart that about 5-30% of time,s it depend from the period, it don't save the full jpeg image, but part of it, variable between about 5 and 30% is white.
Maybe I should give more of 128mb of gpu to raspbian? Any ideas?

**Comment by AndrewFromMelbourne** [comment]
Hi @matteoraggi. Sorry for the delay. No idea really. 128mb sounds like more than enough.

**Comment by martinohanlon** [comment]
I have used raspi2png with stretch using 1080p with 64Mb RAM with no errors.
