### ISSUE TITLE
black screen while taking the screenshot

### ISSUE THREAD

**Issue by natxopedreira** [AndrewFromMelbourne/raspi2png#17]
Hi

Im using you app (thanks!) to take screenshots of a direct frame render app (like raspivid) and sometimes the screen goes to black when i take the snapshot. When this happens one time i can not make it work again (without going black)

Did you know what can cause this behavior "black screen while taking the screenshot"?

**Comment by speedy78** [comment]
I have found similar issue. Did you find a solution?
