### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by michaelhanin** [AndrewFromMelbourne/raspi2png#2]
Hello,

This script work fine when no rotation, but with rotate=1 in kernel, it freeze and does not work .. any idea ? thx

**Comment by chandra50** [comment]
Hi Andrew,
  Revisiting the raspi2png on rotated screen.  Were you able to get some
update on solving the rotated screen problem.

Thanks a lot.
Regards,
Chandra

**Comment by AndrewFromMelbourne** [comment]
Hi Chandra,
Sorry for the very long delay. Other things came up and then I completely forgot. I am sorry!
As you will see above I have finally managed to reproduce the issue and I have raised an issue on the firmware.
The good news is I think I have a work around. Try using the -b option of omxplayer. The option adds a black layer underneath the playing video. As your video is full screen, you won't see it. However, from my experiments by adding the extra layer, the video is no longer distorted. So try
```
omxplay -b yourvideo.mpg
```

**Comment by AndrewFromMelbourne** [comment]
Hi Chandra,

I am sorry that this took so long (on my part). The Raspberry PI firmware has now been fixed (you will need to use rpi-update for now to get the latest firmware). Once the bug was reported on the Raspberry Pi firmware the fix was made very quickly. Once again sorry that it took so long for me to raise the issue. I hope that it now works for you.

Andrew

**Comment by chandra50** [comment]
Hi Andrew,
  Thanks a lot.  It works perfectly.  My sincere gratitude in you
addressing this problem.

 One suggestion for raspi2png - a setting for resolution (to reduce the
file size).

Thanks again.
With kind regards,
Chandra

**Comment by AndrewFromMelbourne** [comment]
Hi Chandra,
Thanks for your patience.

I will have a think about resolution ... so just to be clear are you wanting to reduce the file size or have a smaller (fewer pixel) image. Reducing the file size would be possible if I created a raspi2jpg program, which is possible. Reducing the number of pixels is pretty trivial and could implemented by specifying the desired width (and/or height) on the command line. Let me know.

With regards to this issue, are you happy to close it now?

Thanks,

Andrew

**Comment by chandra50** [comment]
Hi Andrew,
   We are delighted with your solution you have provided and you may close
the issue.  I have tested it a few times.

  Yes, we would like to have a reduced file size as an option to raspi2png.
Currently I am using a program to create a lower resolution jpg file (from
snapshot.png) to reduce the file size.

Thanks.
Regards,
Chandra

**Comment by chandra50** [comment]
Hi Andrew,
  Thanks for all your help, I have been using raspi2png quite a bit.

  Right now it has been painful to reduce the file size for copying the
image to the cloud - if you could kindly provide support for raspi2jpg or a
way to reduce the number of pixel would be great.

Thanks.
Regards,
Chandra

**Comment by AndrewFromMelbourne** [comment]
Hi Chandra,

I am still struggling to understand what you require. You can reduce the number of pixels in the snapshot using either the --width or --height command line options

>For reduced resolution use the --width and/or --height to specify the dimensions of the snapshot. If you just specify one the other is calculated from the the aspect ratio of the screen.

Unfortunately, at the moment that probably won't work for you as the is an [issue open about this feature on rotated displays](https://github.com/AndrewFromMelbourne/raspi2png/issues/6) and [related issue for the Raspberry Pi firmware](https://github.com/raspberrypi/firmware/issues/435).

Could you please explain why using the --width and/or --height options is not a solution for you.

Andrew

**Comment by AndrewFromMelbourne** [comment]
Hi Chandra.

The bug that prevented resizing on rotated screens is now addressed in the latest firmware release.

Andrew

**Comment by chandra50** [comment]
Hi Andrew,
 Thanks a lot. I will test it out this weekend.

With kind regards,
Chandra

**Comment by matttheorbiter** [comment]
I have installed and reinstalled this on my Pi 2. I have successfully taken two screenshot. Then it always fails with raspi2png: vc_dispmanx_snapshot() failed. Anybody have any idea what's happening. Why it works one second, but not the next?

**Comment by matttheorbiter** [comment]
Followup. If I delete the directory. Then completely reinstall, *sometimes* it will work. Sometimes it won't. Maddening. Any help appreciated.

**Comment by AndrewFromMelbourne** [comment]
OK I will see if I can reproduce this. It would be good if you opened a new issue rather than adding to a closed and probably unrelated issue.

**Comment by matttheorbiter** [comment]
Sorry about that. I will. Just was glad to find some people talking about the program and got excited I guess. Thanks.

**Comment by AndrewFromMelbourne** [comment]
No problem. I am the author of the program.

**Comment by matttheorbiter** [comment]
Think I figured out the problem. When Scraping in RetroPie on a Raspberry Pi, while doing the final step, choosing the metadata, raspi2png always fails. Today I can’t get it to fail otherwise, so maybe it has something to do with the scrape utility. So far today raspi2png is working like a champ for me.

Thanks for the program, I will mention it in the credits of the book I’m writing, it’s been indispensable now that I’ve got it running.

Matt



Matt Smith, NBCT
mrmattsmith@comcast.net
AP 12 English/US History/Sociology
Valley High School
Albuquerque, New Mexico
