### ISSUE TITLE
raspi2png fails when using "GL (Full KMS) OpenGL driver"

### ISSUE THREAD

**Issue by martinohanlon** [AndrewFromMelbourne/raspi2png#20]
raspi2png fails with the error:

```
raspi2png: unable to open display 0
```

when using the GL (Full KMS) OpenGL driver, enabled using 

```
sudo raspi-config

Advanced Options > GL Driver
```

**Comment by AndrewFromMelbourne** [comment]
Sorry that I never replied to this. The raspi2png program is very simple and relies on a feature of the GPU. As far as I know the feature I use to capture the screen is not compatible with the new OpenGL driver.

**Comment by bradisbell** [comment]
@AndrewFromMelbourne Do you know if there are alternative methods for capturing the output of the GPU when using OpenGL on the Pi?  (Even if not implemented by your code.)

**Comment by AndrewFromMelbourne** [comment]
Sorry, no I don't.
