### ISSUE TITLE
Install error.

### ISSUE THREAD

**Issue by koutsie** [AndrewFromMelbourne/raspi2png#22]
make: *** [raspi2png] Error 1
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'raspi2png' failed
Hmmm

**Comment by AndrewFromMelbourne** [comment]
Hi @koutsie. What command line did you use to generate the error message?

**Comment by koutsie** [comment]
raspi2png -p hi.png 
i think. its been some time.

**Comment by AndrewFromMelbourne** [comment]
Hi, can you give me a little more information? I don't know what you are asking.
