### ISSUE TITLE
Rotation (again)

### ISSUE THREAD

**Issue by SinisterSpatula** [AndrewFromMelbourne/raspi2png#24]
Hi there, great tool!  I noticed that if my `/boot/config.txt` was using `display_lcd_rotate=1` that raspi2png did not pick up on this and took warped/sideways shots.  If I changed my rotate config to just `display_rotate=1` instead it works fine.  To replicate, just change your rotate line to `display_lcd_rotate=1` and try taking a screenshot.  edit: well another user tells me that they use display_lcd_rotate and it's not an issue for them, so now I'm not so sure on why that fixed it for me.  I'm running retropie 4.5.1 and kernel 4.14.114 when I noticed this, so it might be unique to that.

**Comment by AndrewFromMelbourne** [comment]
Did you ever find a solution? I accepted a pull request in September that hopefully may solve your problem.

**Comment by SinisterSpatula** [comment]
changing my boot/config.txt from display_lcd_rotate=1 to display_rotate=1 was the solution for me, or at least that's what I think fixed it. (I could have been wrong)

**Comment by AndrewFromMelbourne** [comment]
Thanks!
