### ISSUE TITLE
Doesn't work on Raspbian Buster: libpng12 dependency issue

### ISSUE THREAD

**Issue by ZLevine** [AndrewFromMelbourne/raspi2png#26]
I've been using this amazing library for years after setting it up [per this guide](https://howchoo.com/g/mgmym2fimzd/how-to-take-screenshots-on-the-raspberry-pi); however, I tried on a fresh install of Raspbian Buster and get the following error:

```
raspi2png: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

It looks like raspi2png relies on libpng12, which isn't included in the later versions of Raspbian. Additionally, it can't be installed manually since there's no download link for [the armhf version on the package listing](https://packages.ubuntu.com/xenial/armhf/libpng12-0/download).

Any idea what we can do here to get it working? Thanks!

**Comment by AndrewFromMelbourne** [comment]
Let me have a look

**Comment by ZLevine** [comment]
Thanks! Let me know if you need help testing anything out.

**Comment by AndrewFromMelbourne** [comment]
I have pushed a new binary built on Raspbian Buster. Please git it a try and let me know if there are any issues.

**Comment by ZLevine** [comment]
Tested and working! Thanks a ton.
