### ISSUE TITLE
write to stdout

### ISSUE THREAD

**Issue by ktsaou** [AndrewFromMelbourne/raspi2png#5]
Thank you very much for raspi2png!

I would like to make 2 suggestions:
1. It would be useful to support writing to stdout. I normally snapshot the pi screen to send it to a web page. Now I do something like this using inetd:
   
   ``` sh
   echo "HTTP/1.1 200 OK"
   echo "Content-type: image/png"
   echo
   raspi2png -p "/run/snapshot-$$.png" -h $h -w $w
   cat "/run/snapshot-$$.png"
   rm "/run/snapshot-$$.png"
   ```
   
   The extra effort to save and delete the image could be avoided if raspi2png could just write the png image to its stdout.
2. raspi2png is somewhat slow. I don't know if this is because I need it to scale the image, or because the png compression is too complex for a pi.
   
   In any case, it would be perfect if you could speed it up (for example the OMX API may already provide hardware scaling, or it may provide hardware JPEG encoding - I guess it does both because raspistill is a lot faster, capable of capturing and saving many JPEG frames per second - of course from the camera, not the screen).

Anyway, thank you very much. Even the way it is now, raspi2png is very helpful.

**Comment by AndrewFromMelbourne** [comment]
Sorry for the long delay. Thanks for that, so hopefully that is a solution for you. I actually wrote a program that I called raspi2jpg before I wrote raspi2png, but I never put the code up on github.
