### ISSUE TITLE
raspi2png raspi2png: vc_dispmanx_snapshot() failed error

### ISSUE THREAD

**Issue by matttheorbiter** [AndrewFromMelbourne/raspi2png#8]
I have installed and reinstalled this on my Pi 2. I can take one or two snapshots. Then it always fails with raspi2png: vc_dispmanx_snapshot() failed. If I reboot, sometimes it will let me take snapshots, sometimes not. If I delete the directory and reinstall the app, sometimes I can get it to do one or two. Then the error returns. Thanks for your help.

**Comment by AndrewFromMelbourne** [comment]
Hi, sorry I completely missed this issue. Have you managed to resolve the problem? I would think that it may have been an issue with a particular version of the Raspberry Pi Firmware.

**Comment by larryfant** [comment]
At least I have that problem when playing video with omxplayer. Without playing video screencaptures are ok.

**Comment by AndrewFromMelbourne** [comment]
Thanks @larryfant I will see if I can reproduce it.

**Comment by Jabroni** [comment]
Any resolution / update on the issues? Im experiencing same issue, what is wierd is that Im able to take screenshots of videos that have still images on it (using omxplayer), but if there is movement on the video, and I try to run raspi2png,  I get "raspi2png: vc_dispmanx_snapshot() failed "

**Comment by AndrewFromMelbourne** [comment]
No, unfortunately I am pretty short of time these days. The error comes from the Raspberry Pi firmware rather than my code.

**Comment by Jabroni** [comment]
Seems this is being caused cuz of the raspberry is running out of GPU memory. I added 
gpu_mem=96 to my raspberry config.txt and i was able to take the screenshot of the videos that had more motion on it

**Comment by AndrewFromMelbourne** [comment]
Hi @Jabroni. Yes I should have thought of that. Glad you have found a solution/work around to your problem.
